import type {
  CanvasUser,
  CanvasCourse,
  CanvasAssignment,
  CanvasCalendarEvent,
} from "./canvas.types";

// Helper — build an ISO date offset from June 17 2026
const T = (offsetDays: number, hour = 23, min = 59) => {
  const d = new Date("2026-06-17T00:00:00");
  d.setDate(d.getDate() + offsetDays);
  d.setHours(hour, min, 0, 0);
  return d.toISOString();
};

// Helper — build an ISO date from an absolute date string + time
const D = (date: string, hour = 23, min = 59) => {
  const d = new Date(`${date}T00:00:00`);
  d.setHours(hour, min, 0, 0);
  return d.toISOString();
};

// ---------------------------------------------------------------------------
// User
// ---------------------------------------------------------------------------

export const mockUser: CanvasUser = {
  id: 100001,
  name: "Cameron Ryder",
  short_name: "Cameron",
  login_id: "cryder@nwu.edu",
  email: "cryder@nwu.edu",
  avatar_url: "https://example.instructure.com/images/thumbnails/default_avatar.png",
};

// ---------------------------------------------------------------------------
// Courses  (8 courses across two semesters — 5 active this summer)
// ---------------------------------------------------------------------------

export const mockCourses: CanvasCourse[] = [
  {
    id: 2001,
    name: "CS 301 – Data Structures & Algorithms",
    course_code: "CS301",
    start_at: "2026-06-01T00:00:00Z",
    end_at: "2026-08-15T00:00:00Z",
    workflow_state: "available",
    enrollment_term_id: 10,
    uuid: "cs301-uuid-0001",
    color: "#4A90D9",
  },
  {
    id: 2002,
    name: "MATH 220 – Linear Algebra",
    course_code: "MATH220",
    start_at: "2026-06-01T00:00:00Z",
    end_at: "2026-08-15T00:00:00Z",
    workflow_state: "available",
    enrollment_term_id: 10,
    uuid: "math220-uuid-0002",
    color: "#E84040",
  },
  {
    id: 2003,
    name: "ENG 201 – Technical Writing",
    course_code: "ENG201",
    start_at: "2026-06-01T00:00:00Z",
    end_at: "2026-08-15T00:00:00Z",
    workflow_state: "available",
    enrollment_term_id: 10,
    uuid: "eng201-uuid-0003",
    color: "#2ECC71",
  },
  {
    id: 2004,
    name: "PHYS 211 – Physics II: Electromagnetism",
    course_code: "PHYS211",
    start_at: "2026-06-01T00:00:00Z",
    end_at: "2026-08-15T00:00:00Z",
    workflow_state: "available",
    enrollment_term_id: 10,
    uuid: "phys211-uuid-0004",
    color: "#9B59B6",
  },
  {
    id: 2005,
    name: "CS 350 – Operating Systems",
    course_code: "CS350",
    start_at: "2026-06-01T00:00:00Z",
    end_at: "2026-08-15T00:00:00Z",
    workflow_state: "available",
    enrollment_term_id: 10,
    uuid: "cs350-uuid-0005",
    color: "#F39C12",
  },
  {
    id: 2006,
    name: "PSYC 101 – Introduction to Psychology",
    course_code: "PSYC101",
    start_at: "2026-06-01T00:00:00Z",
    end_at: "2026-08-15T00:00:00Z",
    workflow_state: "available",
    enrollment_term_id: 10,
    uuid: "psyc101-uuid-0006",
    color: "#1ABC9C",
  },
  // Completed prior semester courses
  {
    id: 1901,
    name: "CS 201 – Object-Oriented Programming",
    course_code: "CS201",
    start_at: "2026-01-15T00:00:00Z",
    end_at: "2026-05-20T00:00:00Z",
    workflow_state: "completed",
    enrollment_term_id: 9,
    uuid: "cs201-uuid-0007",
    color: "#4A90D9",
  },
  {
    id: 1902,
    name: "MATH 181 – Calculus II",
    course_code: "MATH181",
    start_at: "2026-01-15T00:00:00Z",
    end_at: "2026-05-20T00:00:00Z",
    workflow_state: "completed",
    enrollment_term_id: 9,
    uuid: "math181-uuid-0008",
    color: "#E84040",
  },
];

// ---------------------------------------------------------------------------
// Assignments
// ---------------------------------------------------------------------------

export const mockAssignments: CanvasAssignment[] = [
  // ── CS 301 ──────────────────────────────────────────────────────────────
  {
    id: 3001,
    name: "HW 1 – Linked Lists",
    description: "<p>Implement a singly and doubly linked list in TypeScript. Include insert, delete, search, and reverse operations with unit tests.</p>",
    due_at: T(2),
    points_possible: 100,
    course_id: 2001,
    html_url: "https://example.instructure.com/courses/2001/assignments/3001",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3002,
    name: "HW 2 – Stacks & Queues",
    description: "<p>Implement stack and queue using both arrays and linked lists. Analyze time complexity for each operation.</p>",
    due_at: T(7),
    points_possible: 100,
    course_id: 2001,
    html_url: "https://example.instructure.com/courses/2001/assignments/3002",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3003,
    name: "HW 3 – Binary Search Trees",
    description: "<p>Implement BST with insert, delete, search, min, max, and all three traversals. Include balancing discussion.</p>",
    due_at: T(14),
    points_possible: 100,
    course_id: 2001,
    html_url: "https://example.instructure.com/courses/2001/assignments/3003",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3004,
    name: "HW 4 – Hash Tables",
    description: "<p>Implement a hash table with open addressing and separate chaining. Compare load factor vs. performance.</p>",
    due_at: T(21),
    points_possible: 100,
    course_id: 2001,
    html_url: "https://example.instructure.com/courses/2001/assignments/3004",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3005,
    name: "HW 5 – Heaps & Priority Queues",
    description: "<p>Build a min-heap and use it to implement a priority queue. Solve the k-largest elements problem.</p>",
    due_at: T(28),
    points_possible: 100,
    course_id: 2001,
    html_url: "https://example.instructure.com/courses/2001/assignments/3005",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3006,
    name: "Midterm Project – Graph Algorithms",
    description: "<p>Implement BFS, DFS, Dijkstra's shortest path, and cycle detection on an adjacency list graph. Include a written report analyzing time and space complexity.</p>",
    due_at: T(35),
    points_possible: 250,
    course_id: 2001,
    html_url: "https://example.instructure.com/courses/2001/assignments/3006",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3007,
    name: "HW 6 – Sorting Algorithms",
    description: "<p>Implement merge sort, quicksort, heapsort, and radix sort. Benchmark all four on random and nearly-sorted inputs.</p>",
    due_at: T(42),
    points_possible: 100,
    course_id: 2001,
    html_url: "https://example.instructure.com/courses/2001/assignments/3007",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3008,
    name: "HW 7 – Dynamic Programming",
    description: "<p>Solve: longest common subsequence, 0/1 knapsack, and coin change. Provide memoized and bottom-up solutions.</p>",
    due_at: T(49),
    points_possible: 100,
    course_id: 2001,
    html_url: "https://example.instructure.com/courses/2001/assignments/3008",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3009,
    name: "Final Project – Algorithm Design Portfolio",
    description: "<p>Design and implement solutions for 5 real-world problems using the data structures and algorithms from this course. Include complexity analysis, test suite, and a recorded 10-minute walkthrough.</p>",
    due_at: T(56),
    points_possible: 300,
    course_id: 2001,
    html_url: "https://example.instructure.com/courses/2001/assignments/3009",
    submission_types: ["online_upload", "media_recording"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3010,
    name: "Participation – Week 1 Discussion",
    description: "<p>Post a response comparing array vs. linked list tradeoffs in a real-world scenario. Reply to at least two classmates.</p>",
    due_at: T(4, 23, 59),
    points_possible: 10,
    course_id: 2001,
    html_url: "https://example.instructure.com/courses/2001/assignments/3010",
    submission_types: ["discussion_topic"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3011,
    name: "Participation – Week 3 Discussion",
    description: "<p>Discuss a time when you would choose a BST over a hash table, and vice versa. Cite at least one source.</p>",
    due_at: T(18, 23, 59),
    points_possible: 10,
    course_id: 2001,
    html_url: "https://example.instructure.com/courses/2001/assignments/3011",
    submission_types: ["discussion_topic"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3012,
    name: "Quiz 1 – Big-O Notation",
    description: "<p>15-minute online quiz covering Big-O, Big-Theta, and Big-Omega notation.</p>",
    due_at: T(5, 9, 15),
    points_possible: 25,
    course_id: 2001,
    html_url: "https://example.instructure.com/courses/2001/assignments/3012",
    submission_types: ["online_text_entry"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3013,
    name: "Quiz 2 – Trees & Hashing",
    description: "<p>20-minute online quiz on BST operations and hash collision resolution.</p>",
    due_at: T(19, 9, 15),
    points_possible: 25,
    course_id: 2001,
    html_url: "https://example.instructure.com/courses/2001/assignments/3013",
    submission_types: ["online_text_entry"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },

  // ── MATH 220 ────────────────────────────────────────────────────────────
  {
    id: 3101,
    name: "Problem Set 1 – Vectors & Vector Spaces",
    description: null,
    due_at: T(3),
    points_possible: 50,
    course_id: 2002,
    html_url: "https://example.instructure.com/courses/2002/assignments/3101",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3102,
    name: "Problem Set 2 – Matrix Operations",
    description: null,
    due_at: T(10),
    points_possible: 50,
    course_id: 2002,
    html_url: "https://example.instructure.com/courses/2002/assignments/3102",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3103,
    name: "Problem Set 3 – Systems of Linear Equations",
    description: null,
    due_at: T(17),
    points_possible: 50,
    course_id: 2002,
    html_url: "https://example.instructure.com/courses/2002/assignments/3103",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3104,
    name: "Problem Set 4 – Determinants",
    description: null,
    due_at: T(24),
    points_possible: 50,
    course_id: 2002,
    html_url: "https://example.instructure.com/courses/2002/assignments/3104",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3105,
    name: "Problem Set 5 – Eigenvalues & Eigenvectors",
    description: null,
    due_at: T(31),
    points_possible: 50,
    course_id: 2002,
    html_url: "https://example.instructure.com/courses/2002/assignments/3105",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3106,
    name: "Problem Set 6 – Orthogonality & Least Squares",
    description: null,
    due_at: T(38),
    points_possible: 50,
    course_id: 2002,
    html_url: "https://example.instructure.com/courses/2002/assignments/3106",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3107,
    name: "Problem Set 7 – SVD & Applications",
    description: null,
    due_at: T(45),
    points_possible: 50,
    course_id: 2002,
    html_url: "https://example.instructure.com/courses/2002/assignments/3107",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3108,
    name: "Midterm Exam",
    description: "<p>Covers chapters 1–4 (vectors through determinants). In-class, closed book. One handwritten cheat sheet allowed.</p>",
    due_at: T(22, 10, 0),
    points_possible: 150,
    course_id: 2002,
    html_url: "https://example.instructure.com/courses/2002/assignments/3108",
    submission_types: ["on_paper"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3109,
    name: "Final Exam",
    description: "<p>Comprehensive final. In-class, closed book. Two handwritten cheat sheets allowed.</p>",
    due_at: T(55, 10, 0),
    points_possible: 200,
    course_id: 2002,
    html_url: "https://example.instructure.com/courses/2002/assignments/3109",
    submission_types: ["on_paper"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3110,
    name: "Take-Home Quiz 1 – Gaussian Elimination",
    description: "<p>Complete the 6 problems in the PDF. Show all work.</p>",
    due_at: T(6),
    points_possible: 30,
    course_id: 2002,
    html_url: "https://example.instructure.com/courses/2002/assignments/3110",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3111,
    name: "Matlab Lab 1 – Matrix Computations",
    description: "<p>Complete the guided Matlab exercises and submit your .m file and a PDF of the output.</p>",
    due_at: T(13),
    points_possible: 40,
    course_id: 2002,
    html_url: "https://example.instructure.com/courses/2002/assignments/3111",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3112,
    name: "Matlab Lab 2 – Eigenvalue Applications",
    description: "<p>Use Matlab to analyze Google PageRank via eigenvalues. Submit .m file and written analysis.</p>",
    due_at: T(40),
    points_possible: 40,
    course_id: 2002,
    html_url: "https://example.instructure.com/courses/2002/assignments/3112",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },

  // ── ENG 201 ─────────────────────────────────────────────────────────────
  {
    id: 3201,
    name: "Reading Response 1 – Audience & Purpose",
    description: "<p>One-page response to Markel Ch. 1–2. What makes technical writing different from academic writing?</p>",
    due_at: T(3),
    points_possible: 20,
    course_id: 2003,
    html_url: "https://example.instructure.com/courses/2003/assignments/3201",
    submission_types: ["online_text_entry"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3202,
    name: "Reading Response 2 – Document Design",
    description: "<p>Critique a real-world document (software README, technical manual, etc.) for layout and usability.</p>",
    due_at: T(10),
    points_possible: 20,
    course_id: 2003,
    html_url: "https://example.instructure.com/courses/2003/assignments/3202",
    submission_types: ["online_text_entry"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3203,
    name: "Reading Response 3 – Ethics in Technical Communication",
    description: "<p>Analyze a case of misleading technical documentation (e.g. Boeing 737 MAX manuals). 1–2 pages.</p>",
    due_at: T(17),
    points_possible: 20,
    course_id: 2003,
    html_url: "https://example.instructure.com/courses/2003/assignments/3203",
    submission_types: ["online_text_entry"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3204,
    name: "Reading Response 4 – Instructions & Procedures",
    description: "<p>Evaluate the usability of a set of instructions you use regularly. Propose three improvements.</p>",
    due_at: T(24),
    points_possible: 20,
    course_id: 2003,
    html_url: "https://example.instructure.com/courses/2003/assignments/3204",
    submission_types: ["online_text_entry"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3205,
    name: "Assignment 1 – Instructions Document",
    description: "<p>Write a set of step-by-step instructions for a technical process aimed at a non-expert audience. 3–4 pages, must include at least one diagram or screenshot.</p>",
    due_at: T(15),
    points_possible: 100,
    course_id: 2003,
    html_url: "https://example.instructure.com/courses/2003/assignments/3205",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3206,
    name: "Assignment 2 – Memo Report",
    description: "<p>Write a formal memo report analyzing a technical problem in your field. 4–6 pages, APA citations required.</p>",
    due_at: T(29),
    points_possible: 120,
    course_id: 2003,
    html_url: "https://example.instructure.com/courses/2003/assignments/3206",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3207,
    name: "Technical Report – First Draft",
    description: "<p>Full draft of your 10-page technical report. Will be peer-reviewed in class. Include all sections: abstract, intro, methods, results, discussion, references.</p>",
    due_at: T(37),
    points_possible: 50,
    course_id: 2003,
    html_url: "https://example.instructure.com/courses/2003/assignments/3207",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3208,
    name: "Peer Review – Technical Reports",
    description: "<p>Complete the peer review rubric for your assigned classmate's draft. Submit both the rubric and a 1-page written response.</p>",
    due_at: T(41),
    points_possible: 30,
    course_id: 2003,
    html_url: "https://example.instructure.com/courses/2003/assignments/3208",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3209,
    name: "Technical Report – Final Submission",
    description: "<p>Revised 10-page technical report incorporating peer and instructor feedback. Include a revision log describing changes made.</p>",
    due_at: T(50),
    points_possible: 200,
    course_id: 2003,
    html_url: "https://example.instructure.com/courses/2003/assignments/3209",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3210,
    name: "Presentation – Technical Report",
    description: "<p>8–10 minute presentation on your technical report topic. Must include slides. Q&A follows.</p>",
    due_at: T(53, 13, 0),
    points_possible: 100,
    course_id: 2003,
    html_url: "https://example.instructure.com/courses/2003/assignments/3210",
    submission_types: ["online_upload", "media_recording"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },

  // ── PHYS 211 ────────────────────────────────────────────────────────────
  {
    id: 3301,
    name: "HW 1 – Coulomb's Law & Electric Field",
    description: "<p>Serway & Jewett Ch. 23, problems 1–12. Show all work and include unit analysis.</p>",
    due_at: T(4),
    points_possible: 40,
    course_id: 2004,
    html_url: "https://example.instructure.com/courses/2004/assignments/3301",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3302,
    name: "HW 2 – Gauss's Law",
    description: null,
    due_at: T(11),
    points_possible: 40,
    course_id: 2004,
    html_url: "https://example.instructure.com/courses/2004/assignments/3302",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3303,
    name: "HW 3 – Electric Potential",
    description: null,
    due_at: T(18),
    points_possible: 40,
    course_id: 2004,
    html_url: "https://example.instructure.com/courses/2004/assignments/3303",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3304,
    name: "HW 4 – Capacitance & Dielectrics",
    description: null,
    due_at: T(25),
    points_possible: 40,
    course_id: 2004,
    html_url: "https://example.instructure.com/courses/2004/assignments/3304",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3305,
    name: "HW 5 – Current, Resistance & DC Circuits",
    description: null,
    due_at: T(32),
    points_possible: 40,
    course_id: 2004,
    html_url: "https://example.instructure.com/courses/2004/assignments/3305",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3306,
    name: "HW 6 – Magnetic Fields & Forces",
    description: null,
    due_at: T(39),
    points_possible: 40,
    course_id: 2004,
    html_url: "https://example.instructure.com/courses/2004/assignments/3306",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3307,
    name: "HW 7 – Faraday's Law & Inductance",
    description: null,
    due_at: T(46),
    points_possible: 40,
    course_id: 2004,
    html_url: "https://example.instructure.com/courses/2004/assignments/3307",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3308,
    name: "HW 8 – AC Circuits & Maxwell's Equations",
    description: null,
    due_at: T(53),
    points_possible: 40,
    course_id: 2004,
    html_url: "https://example.instructure.com/courses/2004/assignments/3308",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3309,
    name: "Lab Report 1 – Electrostatics",
    description: "<p>Write up the electrostatics experiment results. Include data tables, error analysis, and conclusion.</p>",
    due_at: T(6),
    points_possible: 60,
    course_id: 2004,
    html_url: "https://example.instructure.com/courses/2004/assignments/3309",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3310,
    name: "Lab Report 2 – Ohm's Law",
    description: "<p>Full lab report on Ohm's Law verification. V-I curves required for all resistor configurations.</p>",
    due_at: T(20),
    points_possible: 60,
    course_id: 2004,
    html_url: "https://example.instructure.com/courses/2004/assignments/3310",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3311,
    name: "Lab Report 3 – RC Circuits",
    description: "<p>Analyze the charging and discharging of a capacitor. Fit exponential curves and extract time constants.</p>",
    due_at: T(34),
    points_possible: 60,
    course_id: 2004,
    html_url: "https://example.instructure.com/courses/2004/assignments/3311",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3312,
    name: "Lab Report 4 – Magnetic Fields",
    description: "<p>Measure and map the magnetic field of a solenoid. Compare to theoretical predictions.</p>",
    due_at: T(48),
    points_possible: 60,
    course_id: 2004,
    html_url: "https://example.instructure.com/courses/2004/assignments/3312",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3313,
    name: "Midterm Exam",
    description: "<p>Covers Ch. 23–26 (electric fields through capacitance). In-class. One equation sheet allowed (provided).</p>",
    due_at: T(23, 11, 0),
    points_possible: 150,
    course_id: 2004,
    html_url: "https://example.instructure.com/courses/2004/assignments/3313",
    submission_types: ["on_paper"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3314,
    name: "Final Exam",
    description: "<p>Comprehensive. In-class. Full equation sheet provided by instructor.</p>",
    due_at: T(57, 11, 0),
    points_possible: 200,
    course_id: 2004,
    html_url: "https://example.instructure.com/courses/2004/assignments/3314",
    submission_types: ["on_paper"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },

  // ── CS 350 – Operating Systems ───────────────────────────────────────────
  {
    id: 3401,
    name: "HW 1 – Processes & Threads",
    description: "<p>Written questions on process states, context switching, and POSIX thread creation.</p>",
    due_at: T(5),
    points_possible: 80,
    course_id: 2005,
    html_url: "https://example.instructure.com/courses/2005/assignments/3401",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3402,
    name: "HW 2 – CPU Scheduling",
    description: "<p>Simulate FCFS, SJF, Round Robin (q=4), and Priority scheduling on the provided workload. Compute average wait time and turnaround time for each.</p>",
    due_at: T(12),
    points_possible: 80,
    course_id: 2005,
    html_url: "https://example.instructure.com/courses/2005/assignments/3402",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3403,
    name: "Programming Project 1 – Shell Implementation",
    description: "<p>Implement a simple Unix shell in C supporting pipes, I/O redirection, background processes, and signal handling.</p>",
    due_at: T(20),
    points_possible: 150,
    course_id: 2005,
    html_url: "https://example.instructure.com/courses/2005/assignments/3403",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3404,
    name: "HW 3 – Deadlock",
    description: "<p>Apply Banker's Algorithm to detect and avoid deadlock in the given resource allocation scenarios.</p>",
    due_at: T(26),
    points_possible: 80,
    course_id: 2005,
    html_url: "https://example.instructure.com/courses/2005/assignments/3404",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3405,
    name: "Programming Project 2 – Thread Synchronization",
    description: "<p>Solve the Dining Philosophers problem and a custom producer-consumer problem using mutexes, semaphores, and condition variables.</p>",
    due_at: T(33),
    points_possible: 150,
    course_id: 2005,
    html_url: "https://example.instructure.com/courses/2005/assignments/3405",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3406,
    name: "HW 4 – Memory Management",
    description: "<p>Trace page replacement algorithms (FIFO, LRU, Optimal) on the provided reference strings. Calculate page fault rates.</p>",
    due_at: T(40),
    points_possible: 80,
    course_id: 2005,
    html_url: "https://example.instructure.com/courses/2005/assignments/3406",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3407,
    name: "Programming Project 3 – Memory Allocator",
    description: "<p>Implement malloc/free using a free list with first-fit, best-fit, and worst-fit strategies. Benchmark fragmentation.</p>",
    due_at: T(47),
    points_possible: 200,
    course_id: 2005,
    html_url: "https://example.instructure.com/courses/2005/assignments/3407",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3408,
    name: "HW 5 – File Systems",
    description: "<p>Design questions on inode structures, directory trees, journaling, and RAID levels.</p>",
    due_at: T(54),
    points_possible: 80,
    course_id: 2005,
    html_url: "https://example.instructure.com/courses/2005/assignments/3408",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3409,
    name: "Midterm Exam",
    description: "<p>Covers processes, scheduling, synchronization, and deadlock. Open notes (two sheets).</p>",
    due_at: T(24, 14, 0),
    points_possible: 150,
    course_id: 2005,
    html_url: "https://example.instructure.com/courses/2005/assignments/3409",
    submission_types: ["on_paper"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3410,
    name: "Final Exam",
    description: "<p>Comprehensive final. Open notes (four sheets).</p>",
    due_at: T(58, 14, 0),
    points_possible: 200,
    course_id: 2005,
    html_url: "https://example.instructure.com/courses/2005/assignments/3410",
    submission_types: ["on_paper"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },

  // ── PSYC 101 ────────────────────────────────────────────────────────────
  {
    id: 3501,
    name: "Reading Quiz 1 – History & Research Methods",
    description: "<p>15-question multiple choice quiz on Myers Ch. 1.</p>",
    due_at: T(3, 9, 0),
    points_possible: 15,
    course_id: 2006,
    html_url: "https://example.instructure.com/courses/2006/assignments/3501",
    submission_types: ["online_text_entry"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3502,
    name: "Reading Quiz 2 – Biological Bases of Behavior",
    description: null,
    due_at: T(10, 9, 0),
    points_possible: 15,
    course_id: 2006,
    html_url: "https://example.instructure.com/courses/2006/assignments/3502",
    submission_types: ["online_text_entry"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3503,
    name: "Reading Quiz 3 – Sensation & Perception",
    description: null,
    due_at: T(17, 9, 0),
    points_possible: 15,
    course_id: 2006,
    html_url: "https://example.instructure.com/courses/2006/assignments/3503",
    submission_types: ["online_text_entry"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3504,
    name: "Reading Quiz 4 – States of Consciousness",
    description: null,
    due_at: T(24, 9, 0),
    points_possible: 15,
    course_id: 2006,
    html_url: "https://example.instructure.com/courses/2006/assignments/3504",
    submission_types: ["online_text_entry"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3505,
    name: "Reading Quiz 5 – Learning",
    description: null,
    due_at: T(31, 9, 0),
    points_possible: 15,
    course_id: 2006,
    html_url: "https://example.instructure.com/courses/2006/assignments/3505",
    submission_types: ["online_text_entry"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3506,
    name: "Reading Quiz 6 – Memory",
    description: null,
    due_at: T(38, 9, 0),
    points_possible: 15,
    course_id: 2006,
    html_url: "https://example.instructure.com/courses/2006/assignments/3506",
    submission_types: ["online_text_entry"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3507,
    name: "Reading Quiz 7 – Thinking & Language",
    description: null,
    due_at: T(45, 9, 0),
    points_possible: 15,
    course_id: 2006,
    html_url: "https://example.instructure.com/courses/2006/assignments/3507",
    submission_types: ["online_text_entry"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3508,
    name: "Reading Quiz 8 – Motivation & Emotion",
    description: null,
    due_at: T(52, 9, 0),
    points_possible: 15,
    course_id: 2006,
    html_url: "https://example.instructure.com/courses/2006/assignments/3508",
    submission_types: ["online_text_entry"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3509,
    name: "Discussion Post 1 – Classical vs. Operant Conditioning",
    description: "<p>Give a real-world example of each type of conditioning from your own life. Reply to two classmates. 200 words minimum.</p>",
    due_at: T(33),
    points_possible: 20,
    course_id: 2006,
    html_url: "https://example.instructure.com/courses/2006/assignments/3509",
    submission_types: ["discussion_topic"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3510,
    name: "Discussion Post 2 – Memory & Studying",
    description: "<p>Apply the spacing effect and retrieval practice to your own study habits. What will you change? Reply to two classmates.</p>",
    due_at: T(40),
    points_possible: 20,
    course_id: 2006,
    html_url: "https://example.instructure.com/courses/2006/assignments/3510",
    submission_types: ["discussion_topic"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3511,
    name: "Research Paper – Psychological Disorder",
    description: "<p>6–8 page APA-formatted paper on a psychological disorder of your choice. Must cite at least 6 peer-reviewed sources. Include DSM-5 criteria, etiology, and treatment options.</p>",
    due_at: T(50),
    points_possible: 150,
    course_id: 2006,
    html_url: "https://example.instructure.com/courses/2006/assignments/3511",
    submission_types: ["online_upload"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3512,
    name: "Exam 1 – Ch. 1–4",
    description: "<p>50 multiple choice + 2 short answer. Covers research methods, neuroscience, sensation, and consciousness.</p>",
    due_at: T(20, 11, 0),
    points_possible: 100,
    course_id: 2006,
    html_url: "https://example.instructure.com/courses/2006/assignments/3512",
    submission_types: ["on_paper"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3513,
    name: "Exam 2 – Ch. 5–8",
    description: "<p>50 multiple choice + 2 short answer. Covers learning, memory, and cognition.</p>",
    due_at: T(41, 11, 0),
    points_possible: 100,
    course_id: 2006,
    html_url: "https://example.instructure.com/courses/2006/assignments/3513",
    submission_types: ["on_paper"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
  {
    id: 3514,
    name: "Final Exam – Comprehensive",
    description: "<p>75 multiple choice + 3 short answer. Covers the full semester with emphasis on Ch. 9–14.</p>",
    due_at: T(57, 11, 0),
    points_possible: 150,
    course_id: 2006,
    html_url: "https://example.instructure.com/courses/2006/assignments/3514",
    submission_types: ["on_paper"],
    workflow_state: "published",
    grading_type: "points",
    omit_from_final_grade: false,
  },
];

// ---------------------------------------------------------------------------
// Calendar Events — lectures, labs, office hours, study sessions, exams
// ---------------------------------------------------------------------------

function generateLectures(): CanvasCalendarEvent[] {
  const events: CanvasCalendarEvent[] = [];
  let id = 5000;

  // [courseId, title, dayOfWeek (0=Sun), startHour, endHour, room]
  const schedules: [number, string, number[], number, number, string][] = [
    [2001, "CS 301 Lecture",          [1, 3, 5], 9,  10, "Science Hall 204"],
    [2001, "CS 301 Office Hours",     [2],       14, 15, "Science Hall 212 (Prof. Huang)"],
    [2001, "CS 301 Office Hours",     [4],       14, 15, "Science Hall 212 (Prof. Huang)"],
    [2002, "MATH 220 Lecture",        [1, 3, 5], 11, 12, "Math Building 101"],
    [2002, "MATH 220 Office Hours",   [2],       10, 11, "Math Building 118 (Prof. Okonkwo)"],
    [2002, "MATH 220 Office Hours",   [5],       13, 14, "Math Building 118 (Prof. Okonkwo)"],
    [2003, "ENG 201",                 [2, 4],    13, 14, "Humanities 305"],
    [2003, "ENG 201 Office Hours",    [3],       11, 12, "Humanities 218 (Prof. Martinez)"],
    [2004, "PHYS 211 Lecture",        [1, 3],    10, 11, "Physics Hall 110"],
    [2004, "PHYS 211 Lab",            [3],       14, 17, "Physics Lab A"],
    [2004, "PHYS 211 Office Hours",   [2],       13, 14, "Physics Hall 104 (Prof. Kim)"],
    [2004, "PHYS 211 Office Hours",   [4],       13, 14, "Physics Hall 104 (Prof. Kim)"],
    [2005, "CS 350 Lecture",          [1, 3, 5], 14, 15, "Engineering 302"],
    [2005, "CS 350 Office Hours",     [2],       11, 12, "Engineering 308 (Prof. Patel)"],
    [2005, "CS 350 Office Hours",     [4],       11, 12, "Engineering 308 (Prof. Patel)"],
    [2006, "PSYC 101",                [2, 4],    11, 12, "Social Sciences 101"],
    [2006, "PSYC 101 Office Hours",   [1],       15, 16, "Social Sciences 215 (Prof. Nguyen)"],
  ];

  const semesterStart = new Date("2026-06-17");

  for (let week = 0; week < 9; week++) {
    for (const [courseId, title, days, startHour, endHour, room] of schedules) {
      for (const dow of days) {
        const day = new Date(semesterStart);
        day.setDate(semesterStart.getDate() + week * 7 + ((dow - semesterStart.getDay() + 7) % 7));

        // Don't generate past the semester end (~Aug 15)
        if (day > new Date("2026-08-15")) continue;

        const startAt = new Date(day);
        startAt.setHours(startHour, 0, 0, 0);
        const endAt = new Date(day);
        endAt.setHours(endHour, 0, 0, 0);

        events.push({
          id: id++,
          title,
          start_at: startAt.toISOString(),
          end_at: endAt.toISOString(),
          type: "event",
          workflow_state: "active",
          context_code: `course_${courseId}`,
          course_id: courseId,
          description: null,
          location_name: room,
          location_address: null,
        });
      }
    }
  }
  return events;
}

// One-off events: exams, review sessions, campus events, holidays
const oneOffEvents: CanvasCalendarEvent[] = [
  // Midterm review sessions
  {
    id: 6001,
    title: "CS 301 Midterm Review Session",
    start_at: T(33, 17, 0),
    end_at:   T(33, 19, 0),
    type: "event",
    workflow_state: "active",
    context_code: "course_2001",
    course_id: 2001,
    description: "<p>Optional review session for the midterm project. Bring your questions.</p>",
    location_name: "Science Hall 204",
    location_address: null,
  },
  {
    id: 6002,
    title: "MATH 220 Midterm Review",
    start_at: T(20, 18, 0),
    end_at:   T(20, 20, 0),
    type: "event",
    workflow_state: "active",
    context_code: "course_2002",
    course_id: 2002,
    description: "<p>In-class review day — bring practice problems.</p>",
    location_name: "Math Building 101",
    location_address: null,
  },
  {
    id: 6003,
    title: "PHYS 211 Midterm Review",
    start_at: T(21, 16, 0),
    end_at:   T(21, 18, 0),
    type: "event",
    workflow_state: "active",
    context_code: "course_2004",
    course_id: 2004,
    description: "<p>Optional review covering Ch. 23–26.</p>",
    location_name: "Physics Hall 110",
    location_address: null,
  },
  {
    id: 6004,
    title: "CS 350 Midterm Review",
    start_at: T(22, 16, 0),
    end_at:   T(22, 18, 0),
    type: "event",
    workflow_state: "active",
    context_code: "course_2005",
    course_id: 2005,
    description: "<p>Review session for midterm — scheduling, synchronization, deadlock.</p>",
    location_name: "Engineering 302",
    location_address: null,
  },
  // Final review sessions
  {
    id: 6010,
    title: "CS 301 Final Project Q&A",
    start_at: T(53, 17, 0),
    end_at:   T(53, 19, 0),
    type: "event",
    workflow_state: "active",
    context_code: "course_2001",
    course_id: 2001,
    description: null,
    location_name: "Science Hall 204",
    location_address: null,
  },
  {
    id: 6011,
    title: "MATH 220 Final Review",
    start_at: T(52, 18, 0),
    end_at:   T(52, 20, 0),
    type: "event",
    workflow_state: "active",
    context_code: "course_2002",
    course_id: 2002,
    description: null,
    location_name: "Math Building 101",
    location_address: null,
  },
  {
    id: 6012,
    title: "PHYS 211 Final Review",
    start_at: T(54, 16, 0),
    end_at:   T(54, 18, 0),
    type: "event",
    workflow_state: "active",
    context_code: "course_2004",
    course_id: 2004,
    description: null,
    location_name: "Physics Hall 110",
    location_address: null,
  },
  // Campus / personal events
  {
    id: 6020,
    title: "Academic Advising Appointment",
    start_at: T(8, 10, 0),
    end_at:   T(8, 11, 0),
    type: "event",
    workflow_state: "active",
    context_code: "user_100001",
    course_id: null,
    description: "<p>Fall 2026 course planning with advisor Dr. Reyes.</p>",
    location_name: "Student Services 204",
    location_address: null,
  },
  {
    id: 6021,
    title: "Career Fair – Tech & Engineering",
    start_at: T(16, 10, 0),
    end_at:   T(16, 15, 0),
    type: "event",
    workflow_state: "active",
    context_code: "user_100001",
    course_id: null,
    description: "<p>Annual campus career fair. Bring résumés. Business casual attire required.</p>",
    location_name: "Student Union Ballroom",
    location_address: null,
  },
  {
    id: 6022,
    title: "Independence Day – No Classes",
    start_at: D("2026-07-04", 0, 0),
    end_at:   D("2026-07-04", 23, 59),
    type: "event",
    workflow_state: "active",
    context_code: "user_100001",
    course_id: null,
    description: null,
    location_name: null,
    location_address: null,
  },
  {
    id: 6023,
    title: "CS Club Meeting",
    start_at: T(6, 18, 0),
    end_at:   T(6, 19, 30),
    type: "event",
    workflow_state: "active",
    context_code: "user_100001",
    course_id: null,
    description: "<p>Bi-weekly CS Club — this week: lightning talks on personal projects.</p>",
    location_name: "Science Hall 101",
    location_address: null,
  },
  {
    id: 6024,
    title: "CS Club Meeting",
    start_at: T(20, 18, 0),
    end_at:   T(20, 19, 30),
    type: "event",
    workflow_state: "active",
    context_code: "user_100001",
    course_id: null,
    description: "<p>Bi-weekly CS Club — guest speaker from industry.</p>",
    location_name: "Science Hall 101",
    location_address: null,
  },
  {
    id: 6025,
    title: "CS Club Hackathon Kickoff",
    start_at: T(34, 17, 0),
    end_at:   T(34, 18, 0),
    type: "event",
    workflow_state: "active",
    context_code: "user_100001",
    course_id: null,
    description: "<p>24-hour hackathon starts at 5 PM Friday. Teams of up to 4. Theme announced at kickoff.</p>",
    location_name: "Science Hall 101",
    location_address: null,
  },
  {
    id: 6026,
    title: "Tutoring – MATH 220",
    start_at: T(9, 15, 0),
    end_at:   T(9, 16, 0),
    type: "event",
    workflow_state: "active",
    context_code: "course_2002",
    course_id: 2002,
    description: null,
    location_name: "Learning Commons",
    location_address: null,
  },
  {
    id: 6027,
    title: "Tutoring – MATH 220",
    start_at: T(23, 15, 0),
    end_at:   T(23, 16, 0),
    type: "event",
    workflow_state: "active",
    context_code: "course_2002",
    course_id: 2002,
    description: null,
    location_name: "Learning Commons",
    location_address: null,
  },
  {
    id: 6028,
    title: "Peer Tutoring – PHYS 211",
    start_at: T(15, 16, 0),
    end_at:   T(15, 17, 0),
    type: "event",
    workflow_state: "active",
    context_code: "course_2004",
    course_id: 2004,
    description: null,
    location_name: "Physics Help Room",
    location_address: null,
  },
  {
    id: 6029,
    title: "Study Group – CS 301",
    start_at: T(13, 19, 0),
    end_at:   T(13, 21, 0),
    type: "event",
    workflow_state: "active",
    context_code: "course_2001",
    course_id: 2001,
    description: null,
    location_name: "Library Room 3B",
    location_address: null,
  },
  {
    id: 6030,
    title: "Study Group – CS 350",
    start_at: T(19, 19, 0),
    end_at:   T(19, 21, 0),
    type: "event",
    workflow_state: "active",
    context_code: "course_2005",
    course_id: 2005,
    description: null,
    location_name: "Library Room 2A",
    location_address: null,
  },
];

export const mockCalendarEvents: CanvasCalendarEvent[] = [
  ...generateLectures(),
  ...oneOffEvents,
];
